// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OopModel;

#nullable disable

namespace OopModel.Migrations
{
    [DbContext(typeof(dbCtx))]
    partial class dbCtxModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OopModel.KakiEmpat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("Habitat")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsBuas")
                        .HasColumnType("bit");

                    b.Property<int>("Kategori")
                        .HasColumnType("int");

                    b.Property<byte>("KembangBiak")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Nafas")
                        .HasColumnType("tinyint");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("kakiempats");
                });

            modelBuilder.Entity("OopModel.Unggas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("Habitat")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsBuas")
                        .HasColumnType("bit");

                    b.Property<bool>("IsKicau")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTerbang")
                        .HasColumnType("bit");

                    b.Property<int>("Kategori")
                        .HasColumnType("int");

                    b.Property<byte>("KembangBiak")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Nafas")
                        .HasColumnType("tinyint");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("unggass");
                });
#pragma warning restore 612, 618
        }
    }
}
